[profile.default]
src = 'packages/contracts/src'
test = 'packages/contracts/test'
out = 'packages/contracts/out'
script = 'packages/contracts/script'
broadcast = 'packages/contracts/broadcast'
cache_path = 'packages/contracts/cache'
libs = ['packages/contracts/lib']
solc = "0.8.19"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config